#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School#for the other iterations
INCREMENT=1
CHECK=10
while [ $INCREMENT -le $CHECK ];
do
	if [ $INCREMENT = 4 ];
	then
		echo "bad luck"
	elif [ $INCREMENT = 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((INCREMENT++))
done
